# Generated by Django 3.1.7 on 2021-03-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('time', models.DateTimeField()),
                ('ticker_symbol', models.TextField()),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
