# Generated by Django 3.1.7 on 2021-03-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20210326_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='owner',
        ),
    ]
