# Generated by Django 3.1.7 on 2021-03-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_stockprice_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='owner',
        ),
    ]
